# Generated by Django 4.1.1 on 2022-10-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drusas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
